In [1]:

from io import StringIO
import requests
import json
import pandas as pd
import numpy as np

# @hidden_cell
# This function accesses a file in your Object Storage. The definition contains your credentials.
# You might want to remove those credentials before you share your notebook.
def get_object_storage_file_with_credentials_63f2dc1df232458db8431e5111d801de(container, filename):
    """This functions returns a StringIO object containing
    the file content from Bluemix Object Storage."""

    url1 = ''.join(['https://identity.open.softlayer.com', '/v3/auth/tokens'])
    data = {'auth': {'identity': {'methods': ['password'],
            'password': {'user': {'name': 'member_daf273ebef271a59dacfbbd2c8c1d6ce70c9b215','domain': {'id': 'bff414f8f6fe40c7a77ed050397d07db'},
            'password': 'c7,~7.bf/~HXUoRL'}}}}}
    headers1 = {'Content-Type': 'application/json'}
    resp1 = requests.post(url=url1, data=json.dumps(data), headers=headers1)
    resp1_body = resp1.json()
    for e1 in resp1_body['token']['catalog']:
        if(e1['type']=='object-store'):
            for e2 in e1['endpoints']:
                        if(e2['interface']=='public'and e2['region']=='dallas'):
                            url2 = ''.join([e2['url'],'/', container, '/', filename])
    s_subject_token = resp1.headers['x-subject-token']
    headers2 = {'X-Auth-Token': s_subject_token, 'accept': 'application/json'}
    resp2 = requests.get(url=url2, headers=headers2)
    return StringIO(resp2.text)

df= pd.read_csv(get_object_storage_file_with_credentials_63f2dc1df232458db8431e5111d801de('LendingClubcasestudy', 'Cleaned_and_featured_engineered_accepted_data.csv'))
df.head()



/usr/local/src/conda3_runtime/4.1.1/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0       id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
0           1  1077430    1314167       2500         2500             2500   
1           3  1076863    1277178      10000        10000            10000   
2           4  1075358    1311748       3000         3000             3000   
3           6  1069639    1304742       7000         7000             7000   
4           7  1072053    1288686       3000         3000             3000   

   term  int_rate  installment grade    ...     acc_now_delinq  \
0    60     15.27        59.83     C    ...                  0   
1    36     13.49       339.31     C    ...                  0   
2    60     12.69        67.79     B    ...                  0   
3    60     15.96       170.08     C    ...                  0   
4    36     18.64       109.43     E    ...                  0   

  chargeoff_within_12_mths  delinq_amnt pub_rec_bankruptcies  tax_liens  \
0                        0            0                    0          0   
1                        0            0                    0          0   
2                        0            0                    0          0   
3                        0            0                    0          0   
4                        0            0                    0          0   

  fico_range meanfico last_fico_range last_meanfico credit_age  
0    740-744      742           0-499           249         17  
1    690-694      692         600-604           602         20  
2    695-699      697         690-694           692         21  
3    690-694      692         650-654           652         11  
4    660-664      662         685-689           687          7  

[5 rows x 70 columns]

In [2]:
df=df.drop(df.columns[0], axis=1)
df.head(3)

id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  term  \
0  1077430    1314167       2500         2500             2500    60   
1  1076863    1277178      10000        10000            10000    36   
2  1075358    1311748       3000         3000             3000    60   

   int_rate  installment grade sub_grade    ...     acc_now_delinq  \
0     15.27        59.83     C        C4    ...                  0   
1     13.49       339.31     C        C1    ...                  0   
2     12.69        67.79     B        B5    ...                  0   

   chargeoff_within_12_mths delinq_amnt  pub_rec_bankruptcies tax_liens  \
0                         0           0                     0         0   
1                         0           0                     0         0   
2                         0           0                     0         0   

  fico_range meanfico last_fico_range last_meanfico credit_age  
0    740-744      742           0-499           249         17  
1    690-694      692         600-604           602         20  
2    695-699      697         690-694           692         21  

[3 rows x 69 columns]

In [3]:
#Compute the corelation between the features to determine the relationship between all the features
correlations_technique1 = df.corr(method='pearson')
correlations_technique1.ix[6:7,0:14]

id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
int_rate  0.060813   0.056434   0.293904     0.297219         0.284328   

              term  int_rate  installment  emp_length  annual_inc  zip_code  \
int_rate  0.426045       1.0     0.272679    0.016459    0.057697  0.006228   

               dti  delinq_2yrs  earliest_cr_line_year  
int_rate  0.122752      0.15693               0.085455

In [4]:
#Compute the corelation between the features to determine the relationship between all the features
correlations_technique1.ix[6:7,14:26]

fico_range_low  fico_range_high  inq_last_6mths  \
int_rate       -0.696477        -0.696477        0.178261   

          mths_since_last_delinq  mths_since_last_record  open_acc   pub_rec  \
int_rate                0.146765                0.093559  0.033109  0.098536   

          revol_bal  revol_util  total_acc  out_prncp  out_prncp_inv  
int_rate   0.079743    0.439845  -0.009032       0.01           0.01

In [5]:
#Compute the corelation between the features to determine the relationship between all the features
correlations_technique1.ix[6:7,26:36]

total_pymnt  total_pymnt_inv  total_rec_prncp  total_rec_int  \
int_rate     0.289952         0.280407         0.171128       0.510032   

          total_rec_late_fee  recoveries  collection_recovery_fee  \
int_rate             0.09713     0.12231                 0.074636   

          last_pymnt_amnt  last_credit_pull_d_year  last_fico_range_high  
int_rate         0.143461                 0.138951             -0.308263

In [6]:
#Compute the corelation between the features to determine the relationship between all the features
correlations_technique1.ix[6:7,36:47]

last_fico_range_low  collections_12_mths_ex_med  policy_code  \
int_rate            -0.241328                         NaN          NaN   

          acc_now_delinq  chargeoff_within_12_mths  delinq_amnt  \
int_rate         0.00208                       NaN     0.008226   

          pub_rec_bankruptcies  tax_liens  meanfico  last_meanfico  credit_age  
int_rate              0.082421   0.001509 -0.696477      -0.278402   -0.038853

In [7]:
from sklearn.preprocessing import LabelEncoder

#using label encoder to convert categorical columns into numeric values
def dummyEncode(df):
        columnsToEncode = list(df)
        le = LabelEncoder()
        for feature in columnsToEncode:
            try:
                df[feature] = le.fit_transform(df[feature])
            except:
                print('Error encoding '+feature)
        return df

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression



#my_list=['term','revol_util','total_rec_int','meanfico','int_rate']
pearson_df=df[['term','revol_util','total_rec_int','meanfico','int_rate']]

pearson_df=pearson_df.dropna(how='any') 
pearson_df=dummyEncode(pearson_df)

#X_train=df
#random split method for creating the training and test splits
X_train_pearson, X_test_pearson, Y_train_pearson, Y_test_pearson = train_test_split(pearson_df.ix[:, pearson_df.columns != 'int_rate'], pearson_df.int_rate, test_size=0.2, random_state=0)

print("Starting Linear Regression algorithm")
linear_reg = LinearRegression()
fit=linear_reg.fit(X_train_pearson, Y_train_pearson)

print ("Intercept is ",linear_reg.intercept_)
print("Coefficient is ",linear_reg.coef_)
#print(lm.predict([18,3,0,4]))
print("Training score is ",linear_reg.score(X_train_pearson, Y_train_pearson))

#np.mean((linear_reg.predict(X_test)-Y_test)**2)
print("Testing score is ",linear_reg.score(X_test_pearson, Y_test_pearson))

Starting Linear Regression algorithm
Intercept is  248.334544877
Coefficient is  [  6.87206449e+01   5.50651687e-03   3.02501006e-03  -8.79293501e+00]
Training score is  0.704421893325
Testing score is  0.695886688892


In [9]:
from sklearn import feature_selection

percentile_df=df
percentile_df=percentile_df.dropna(how='any') 
percentile_df=dummyEncode(percentile_df)

X_train_percentile, X_test_percentile, Y_train_percentile, Y_test_percentile = train_test_split(percentile_df.ix[:, percentile_df.columns != 'int_rate'], percentile_df.int_rate, test_size=0.2, random_state=0)
feature_names = percentile_df.columns

fs = feature_selection.SelectPercentile(feature_selection.chi2, percentile=20)
X_train_fs = fs.fit_transform(X_train_percentile, Y_train_percentile)

print ('All features:', feature_names)
print ('Scores of these features:', fs.scores_)
print ('***Features sorted by score:', [feature_names[i] for i in np.argsort(fs.scores_)[::-1]])
print ('Peeking into first few samples (before and after):')
print (X_train_percentile[:10])
print (X_train_fs[:10])


/usr/local/src/conda3_runtime/4.1.1/lib/python3.5/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


All features: Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose',
       'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'earliest_cr_line_year', 'fico_range_low',
       'fico_range_high', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt',
       'next_pymnt_d', 'last_credit_pull_d', 'grade_based_on_inq_last_6mths',
       'last_credit_pull_d_year', 'last_fico_range_high',
  

In [12]:

lasso_df=df

del lasso_df['last_pymnt_d']

del lasso_df['next_pymnt_d']

In [13]:
from sklearn.linear_model import RandomizedLasso
lasso_df=df

lasso_df=dummyEncode(lasso_df)
X=lasso_df.ix[:, lasso_df.columns != 'int_rate']
Y=lasso_df.int_rate

rlasso = RandomizedLasso(alpha=0.025)
rlasso.fit(X, Y)
 
print( "Features sorted by their score:")
print (sorted(zip(map(lambda x: round(x, 4), rlasso.scores_), 
                 names), reverse=True))

Features sorted by their score:


NameError: name 'names' is not defined

In [92]:
df.columns


Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose',
       'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'earliest_cr_line_year', 'fico_range_low',
       'fico_range_high', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt', 'last_credit_pull_d',
       'grade_based_on_inq_last_6mths', 'last_credit_pull_d_year',
       'last_fico_range_high', 'last_fico_range_low',
       'collections_12_mt

In [37]:
from sklearn.decomposition import PCA

pca = PCA(n_components=4)
fit = pca.fit(X_train)
print(fit.components_)


PCA(copy=True, iterated_power='auto', n_components=4, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)
[[ 0.00209055  0.0019957   0.99999504 -0.00125412]
 [ 0.01599417 -0.54119303  0.00210103  0.84074364]
 [ 0.0051896   0.84088509 -0.0010103   0.54118788]
 [-0.99985643 -0.00428851  0.0021192   0.01625526]]
